# Generated by Django 4.0.4 on 2022-05-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='/image')),
            ],
        ),
    ]
